### ISSUE TITLE
Raad.env not correct in service.initialize

### ISSUE THREAD

**Issue by net1957** [colinsurprenant/raad#7]
In my application I did setup the environment in the initialize method.
So i changed it to 'my_env = Raad.env'
But it's always the default 'development' value.
If i move the statement to the start method it return the correct value (from the -e option)

any idea ?

**Comment by colinsurprenant** [comment]
Yup, you are right. The Runner, which sets the env according to the -e option (or default to dev), is initialized right after the service, so any env set in your service constructor gets overwritten.

This issue also relates to issue #4. I agree that raad should be completely initialized before the service constructor is called so that it is possible to set the env or use the logger etc.

I will fix this.

Colin.

**Comment by colinsurprenant** [comment]
fixed in 0.5.0.
